# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Artist.create!(name: "Insane Clown Posse", years_active: "1991-present", bio:"Insane Clown Posse (abbreviated as ICP), is an American hip hop duo composed of Violent J (Joseph Bruce) and Shaggy 2 Dope (Joseph Utsler). ICP has earned two platinum and five gold albums. According to Nielsen SoundScan, the entire catalog of the group has sold 6.5 million units in the United States and Canada as of April 2007. The group has established a dedicated following called Juggalos numbering in the 'tens of thousands'.", full_bio: "https://www.last.fm/music/Insane+Clown+Posse/+wiki", image: "https://images.sk-static.com/images/media/profile_images/artists/48999/huge_avatar")
Artist.create!(name: "Necro", years_active: "2009-present", bio: " Ron Raphael Braunstein (born June 7, 1976), better known by his stage-name Necro, is an American rapper from Brooklyn. He is the owner of Psycho+Logical-Records founded November 1999. He is the younger brother of rapper Ill Bill.", full_bio:"https://www.last.fm/music/Necro/+wiki", image: "https://m.media-amazon.com/images/I/71wQUp4rTRL._SX355_.jpg")
Artist.create!(name: "Gravediggaz", years_active: "1993-present", bio: "Gravediggaz was an American hip-hop group from New York City, known for its dark sense of humor and abrasive, menacing soundscapes. Gravediggaz blended hardcore hip hop, gangsta rap and heavy metal with horror elements to pioneer the hip-hop subgenre of horrorcore.", full_bio: "https://www.last.fm/music/Gravediggaz/+wiki", image: "https://m.media-amazon.com/images/I/71wQUp4rTRL._SX355_.jpg")
Artist.create!(name: "Twiztid", years_active: "1997-present", bio: "Twiztid (previously House of Krazees) is an American hip hop duo from Detroit, Michigan. The group is composed of Jamie Madrox (Jamie Spaniolo) and Monoxide Child (Paul Methric). Twiztid performs a style of hardcore hip hop known as horrorcore. They have released seven studio albums, five extended play and have participated in countless compilations. Twiztid's sound is described as having an open obsession with serial-killer horror films, and lyrics related to their roots in Detroit's east side.", full_bio: "https://www.last.fm/music/Twiztid/+wiki", image: "https://static.wikia.nocookie.net/rap/images/f/f5/Twizitd.jpg/revision/latest?cb=20130520210641")
Artist.create!(name: "Tech N9ne", years_active: "1991-present", bio: "Aaron Dontez Yates (born November 8, 1971 in Kansas City, Missouri), better known by his stage name Tech N9ne or Tecca Nina is an American rapper, co-owner of Strange Music Records and actor. His career has spanned over 24 years, during which he has released eleven albums. According to the He's a Mental Giant Songfacts, his stage name originated from the TEC-9 semi-automatic handgun, given to him by rapper Black Walt due to his fast rhyming style. (Tech is short for technique and 9 is the number of completion. That's why he says the technique's complete so often.)", full_bio: "https://www.last.fm/music/Tech+N9ne/+wiki", image: "https://www.billboard.com/wp-content/uploads/media/Tech-N9ne-2018-cr-denny-illic-billboard-1548.jpg")
Artist.create!(name:, years_active:, bio:, full_bio:, image:)
Artist.create!(name:, years_active:, bio:, full_bio:, image:)
Artist.create!(name:, years_active:, bio:, full_bio:, image:)
Artist.create!(name:, years_active:, bio:, full_bio:, image:)
Artist.create!(name:, years_active:, bio:, full_bio:, image:)
Artist.create!(name:, years_active:, bio:, full_bio:, image:)
Artist.create!(name:, years_active:, bio:, full_bio:, image:)
Artist.create!(name:, years_active:, bio:, full_bio:, image:)
Artist.create!(name:, years_active:, bio:, full_bio:, image:)
Artist.create!(name:, years_active:, bio:, full_bio:, image:)
Artist.create!(name:, years_active:, bio:, full_bio:, image:)
Artist.create!(name:, years_active:, bio:, full_bio:, image:)
Artist.create!(name:, years_active:, bio:, full_bio:, image:)
Artist.create!(name:, years_active:, bio:, full_bio:, image:)
Artist.create!(name:, years_active:, bio:, full_bio:, image:)
Artist.create!(name:, years_active:, bio:, full_bio:, image:)
Artist.create!(name:, years_active:, bio:, full_bio:, image:)
Artist.create!(name:, years_active:, bio:, full_bio:, image:)
Artist.create!(name:, years_active:, bio:, full_bio:, image:)
Artist.create!(name:, years_active:, bio:, full_bio:, image:)
Artist.create!(name:, years_active:, bio:, full_bio:, image:)
Artist.create!(name:, years_active:, bio:, full_bio:, image:)
Artist.create!(name:, years_active:, bio:, full_bio:, image:)
Artist.create!(name:, years_active:, bio:, full_bio:, image:)
Artist.create!(name:, years_active:, bio:, full_bio:, image:)
Artist.create!(name:, years_active:, bio:, full_bio:, image:)
Artist.create!(name:, years_active:, bio:, full_bio:, image:)
Artist.create!(name:, years_active:, bio:, full_bio:, image:)
Artist.create!(name:, years_active:, bio:, full_bio:, image:)
Artist.create!(name:, years_active:, bio:, full_bio:, image:)
Artist.create!(name:, years_active:, bio:, full_bio:, image:)
Artist.create!(name:, years_active:, bio:, full_bio:, image:)