# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Artist.create!(name: "Insane Clown Posse", years_active: "1991-present", bio:"Insane Clown Posse (abbreviated as ICP), is an American hip hop duo composed of Violent J (Joseph Bruce) and Shaggy 2 Dope (Joseph Utsler). ICP has earned two platinum and five gold albums. According to Nielsen SoundScan, the entire catalog of the group has sold 6.5 million units in the United States and Canada as of April 2007. The group has established a dedicated following called Juggalos numbering in the 'tens of thousands'. 

Founded in Detroit in 1989, Insane Clown Posse performs a style of hardcore hip hop known as horrorcore and is known for its elaborate live performances. Originally known as JJ Boyz and Inner City Posse, the group introduced supernatural- and horror-themed lyrics as a means of distinguishing itself stylistically. The duo founded the independent record label Psychopathic Records with Alex Abbiss as manager, and produced and starred in the feature films Big Money Hustlas and Big Money Rustlas. They formed their own professional wrestling promotion, Juggalo Championship Wrestling, and later collaborated with many hip hop and rock musicians.

The songs of Insane Clown Posse center thematically on the mythology of the Dark Carnival, a metaphoric limbo in which the lives of the dead are judged by one of several entities. The Dark Carnival is elaborated through a series of stories called Joker's Cards, each of which offers a specific lesson designed to change the 'evil ways' of listeners before 'the end consumes us all'. The original lineup of Insane Clown Posse was John Utsler (John Kickjazz), Joe Bruce (Violent J) and Joey Utsler (Shaggy 2 Dope). John Utsler left before Carnival of Carnage was released in 1992.

Insane Clown Posse's performance style is often described as horrorcore hip hop, which 'utilize shocking (and blatantly over-the-top) narratives to give an over-exaggerated, almost cartoon-like version of urban deprivation in Detroit', according to author Sara Cohen. Bruce and Utsler describe many of their lyrics as being tongue-in-cheek. The group's early work features a raw, minimalistic sound, which later evolved into a more rock-oriented style. The group's lyrics serve as morality tales, with songs focusing on subjects such as cannibalism, murder and necrophilia. Insane Clown Posse's debut album, Carnival of Carnage, features a politically-oriented focus, criticizing elitism and prejudice against those who live in the ghetto, while the album's liner notes criticize the Gulf War. The group's lyrics have opposed racism, bigotry, domestic violence, and child abuse.

Insane Clown Posse has covered songs by Geto Boys, Sly Fox, and Above the Law. Bruce and Utsler refer to Ice Cube, Awesome Dre, Geto Boys, and Esham as influences on their own music, while Bruce has expressed admiration for Gong, Pearl Jam, and Michael Jackson. Mike E. Clark's production for the group incorporates elements such as 'carnival organ riffs, power chords and shotgun blasts…banjolike plucking and Van Halen-esque guitar squeals', while Bruce and Utsler sometimes alternate between rapping and screaming. Bruce has credited pop music as an influence on some of the group's material, even terming the music 'Wicked Pop'. Bruce has also stated 'We do our own genre of music'. In his review of The Tempest, Allmusic's David Jeffries writes that Bruce and Utsler 'in a carnival barker fashion that fits with their circus motif, their Insane Clown disguises, and Mike E. Clark's big top-inspired production.' Insane Clown Posse has influenced similar acts, such as Axe Murder Boyz, Blaze Ya Dead Homie and Boondox.

", image: "https://images.sk-static.com/images/media/profile_images/artists/48999/huge_avatar")
Artist.create!(name: "Necro", years_active: "2009-present", bio: " Ron Raphael Braunstein (born June 7, 1976), better known by his stage-name Necro, is an American rapper from Brooklyn. He is the owner of Psycho+Logical-Records founded November 1999. He is the younger brother of rapper Ill Bill.

Necro was born in Brooklyn, New York and grew up in the Glenwood Houses, where he lived for eight years from about 6 years old to age 14, when he moved to Canarsie. Born into a Jewish family, he is the son of Israeli expatriates, with ancestry from Israel and Romania. Necro's father was a Romanian-born Israeli soldier and his mother an Orthodox baal teshuva.

He began his musical career at 11, playing in a death metal band named Injustice. He made a transition from heavy metal to hip hop. In 1988, he started rapping after being influenced by his older brother, rapper Ill Bill. Necro derived his stage-name from the Slayer song 'Necrophiliac'. Before that he called himself 'Mad Mooney', which was a character from a Clive Barker book. He made his first demo in about 1990 and won a demo battle contest on the Stretch Armstrong and Bobbito show on WKCR-FM. In about 1993 Necro started rapping full-time and made a demo called 'Do The Charles Manson'. In 1995 he proceeded to rap on the Wildman Steve and DJ Riz show WBAU 90.3FM.

Necro plays a hip-hop subgenre called horrorcore. He has played rap metal and has combined rap with death metal music. Necro refers to his music as 'death rap' to describe his style of ultraviolent hip hop and to distinguish himself from other genre labels created by the media. His music combines death metal beats with explicit raps about violence, death, the occult, drugs and sex.

Necro is known for releasing conceptual songs. Songs have tackled topics like the Manson murders: 'Creepy Crawl' 'Cockroaches', 'Scalpel', 'The 12 King Pimp Commandments', 'Dead Body Disposal', 'The Human Traffic King', 'White Slavery' 'I Need Drugs', 'Food For Thought', 'S.T.D.', picking up women ('86 Measures of Game'), cannibalism ('Human Consumption'), suicide ('You Did It'), bondage and sex games ('EdgePlay'), watersports and micturition ('Piss'), life as a pimp ('Out the Pocket'), a revenge tale ('Some Get Back (Revenge)'), and war narratives ('First Blood').

Necro is a devoted fan of the 1983 film Scarface. Necro sampled the main character from Scarface, Tony Montana, in 'Cockroaches'. Necro has also rapped, 'I live scarface scenes' in 'Gory Days', and rapped Montana's infamous quote, 'you fuck with me you fucking with the best', whilst sampling the quote simultaneously in 'asBESTos'. Necro also took the title from 'Push It to the Limit' which appeared in the film's soundtrack and used the title for his own song 'Push it to the Limit'. Al Pacino's work besides Scarface plays a recurrent theme throughout Necro's work. Necro's new collaboration with Kool G Rap is called The Godfathers as is the movie The Godfather that made a star of Al Pacino. In 'asBESTos', Necro raps, 'I'm completely rehabilitated, reinvigorated, reassimilated' which is taken directly from an Al Pacino quote in Carlito's Way.", image: "https://m.media-amazon.com/images/I/71wQUp4rTRL._SX355_.jpg")
Artist.create!(name: "Gravediggaz", years_active: "1993-present", bio: "Gravediggaz was an American hip-hop group from New York City, known for its dark sense of humor and abrasive, menacing soundscapes. Gravediggaz blended hardcore hip hop, gangsta rap and heavy metal with horror elements to pioneer the hip-hop subgenre of horrorcore. 

The group was formed in 1992, bringing together Prince Paul (The Undertaker), Frukwan (The Gatekeeper), Poetic (The Grym Reaper) and RZA (The RZArector). It came about largely due to the efforts of Prince Paul. Frukwan and Prince Paul were previously together in the group Stetsasonic. According to Frukwan, the group's name means 'digging graves of the mentally dead, and it stood for resurrecting the mentally dead from their state of unawareness and ignorance.' The group's lyrics mix black humor (regarding topics such as suicide, death, killing, psychopathy, hell, etc.), criticism regarding the music industry, cartoonish violence reminiscent of the Geto Boys, and esoteric references to the Nation of Gods and Earths. The group pioneered the horrorcore genre.

The group's first album was originally to be titled Niggamortis; however, this potentially risqué title was changed to 6 Feet Deep for the American market (European versions of the album retained the original title, and also included the bonus track 'Pass the Shovel'); it was released on August 9, 1994. The four members adopted Gravedigga alter egos for their work with the group: RZA became The RZArector, Poetic became The Grym Reaper, Prince Paul became The Undertaker, and Frukwan became The Gatekeeper. In 1995, the three rapping members (without Prince Paul) released a collaborative EP titled 'The_Hell_E.P.' with UK trip hop artist Tricky.

The second full-length Gravediggaz album The Pick, the Sickle and the Shovel was less humorous, dealing more with social and political issues; it also used calmer and more conventional production. Prince Paul played a considerably smaller role in the making of this album, with many of the production duties now taken care of by RZA and his Wu-Tang affiliates (including True Master and 4th Disciple).

A bootleg Gravediggaz album surfaced in 1998, called Scenes From The Graveyard. It featured seven unreleased tracks plus some remixes from the first two albums.

Gravediggaz recruited DJ Diamond J. Poetic died of colon cancer in July 2001. Frukwan stated in an interview not long after Poetic's death that a new album using leftover Poetic material would be released. Nightmare in A-Minor, the third official album for Gravediggaz, came out in 2001; it featured two of the original members, Poetic and Frukwan. This album was their darkest work yet, including many references to Poetic's struggle with cancer, as well as apocalyptic themes to do with the teachings of the Five Percent Nation. Although RZA did not take part in the album, some Wu-Tang Clan affiliates such as 4th Disciple, True Master and Beretta 9 were involved. The album was mostly produced by Poetic and Frukwan. A different version of the album (minus the song 'Better Wake Up') was released in 2002, for which some of the tracks created by Poetic were replaced or altered.

In 2003 Frukwan released his debut solo album, Life. The fourth Gravediggaz album 6 Feet Under was released in 2004 by Cleopatra Records and featured songs from Nightmare in A-Minor and Life. According to Frukwan, he had nothing to do with the release and claimed that song titles were changed without permission, making it an unauthorized release.

In 2010, Gravediggaz recorded a new song, '2 More Cups of Blood'. In 2011, it was announced that the group had been recording new tracks involving Shabazz The Disciple & Killah Priest.

In 2018, Gatekeeper released '1 Cup of Blood' under the Gravediggaz name.", image: "https://m.media-amazon.com/images/I/71wQUp4rTRL._SX355_.jpg")
Artist.create!(name: "Twiztid", years_active: "1997-present", bio: "Twiztid (previously House of Krazees) is an American hip hop duo from Detroit, Michigan. The group is composed of Jamie Madrox (Jamie Spaniolo) and Monoxide Child (Paul Methric). Twiztid performs a style of hardcore hip hop known as horrorcore. They have released seven studio albums, five extended play and have participated in countless compilations. Twiztid's sound is described as having an open obsession with serial-killer horror films, and lyrics related to their roots in Detroit's east side.
Twiztid's debut album, Mostasteless, was originally released independently by Psychopathic in 1997, but was pulled, then re-released a year later on Twiztid's new label; Island with a somewhat different track listing as a result of uncleared samples in a few songs in the original release.

On October 31, 2000, Twiztid released their second studio album, Freek Show. The album peaked at #51 on the Billboard 200. In 2002, Twiztid released the extended play Mirror Mirror. Mirror Mirror peaked at #5 on the Top Independent Albums chart, and #103 on the Billboard 200.

In 2003, Twiztid released its third studio album, The Green Book. The Green Book peaked at #2 on the Top Independent Charts and #52 on the Billboard 200.

On June 28, 2005, Twiztid released its fourth studio album, Man's Myth, Vol. 1 the first half of a double album concluding with Mutant, Vol. 2 , released the following month. Man's Myth focuses on the angst of growing up in a lying world, while Mutant deals with the outcome of this upbringing. Man's Myth peaked at #4 on the Top Independent Albums chart, #62 on the Top Internet Albums chart and the Billboard 200. Mutant peaked at #11 on the Top Independent Albums chart, #80 on the Billboard 200, and #215 on the Top Internet Albums chart.

On July 4, 2007, Twiztid released its sixth studio album, Independents Day. The album featured guest appearances from rappers signed to independent record labels, such as The Dayton Family, Tha Dogg Pound, Hed PE frontman Jahred Shane, Tech N9ne and Krizz Kaliko. It also notably features appearances by D12 members Proof and Bizarre. Proof's colaboration with Twiztid entitled, 'How I Live' was Proof's last song before his death in April 2007. The album peaked at #4 on the Top Independent Albums chart, #9 on the Top Rap Albums chart and #57 on the Billboard 200.

On March 17, 2009, Twiztid released its seventh studio album, W.I.C.K.E.D (Wish I Could Kill Every Day). W.I.C.K.E.D is Twiztid's currently highest charting album, peaking at #11 on the Billboard 200, #4 on the Top Rap Albums chart, and #1 on the Top Independent Albums chart.

Twiztid's ninth studio album, 'Heartbroken & Homicidal,' was released on September 21, 2010.

On October 22nd, 2012 Twiztid released their tenth studio album Abominationz. It featured The Insane Clown Posse, and Royce Da 5'9.

On December 12th, 2012 the group announced via Twitter and Facebook that they have parted ways with Psychopathic Records.", image: "https://static.wikia.nocookie.net/rap/images/f/f5/Twizitd.jpg/revision/latest?cb=20130520210641")
Artist.create!(name: "Tech N9ne", years_active: "1991-present", bio: "Aaron Dontez Yates (born November 8, 1971 in Kansas City, Missouri), better known by his stage name Tech N9ne or Tecca Nina is an American rapper, co-owner of Strange Music Records and actor. His career has spanned over 24 years, during which he has released eleven albums. According to the He's a Mental Giant Songfacts, his stage name originated from the TEC-9 semi-automatic handgun, given to him by rapper Black Walt due to his fast rhyming style. (Tech is short for technique and 9 is the number of completion. That's why he says the technique's complete so often.)

His tenth studio album, K.O.D., was released October 27, 2009. He has spent his illustrious career making sure he`s been grinding harder than the average rapper, and is the best selling artist out of his hometown. With nine solo albums and two powerhouse collaboration projects under his belt, the Kansas City MC`s flow is sharper and slicker than it`s ever been.
“This is another roller coaster ride,” explains TECH N9NE about the release. “When it came time for Sickology 101, I knew I wanted to do a collabo album based on the study of being sick. It`s a beginner`s course for people who don`t know how to be sick lyrically or how to choose sick beats. It all starts with beats because they tell me exactly what to do.” Epic beats from YoungFyre, Wyshmaster, Seven and Matic Lee set the stage for TECH N9NE to weave his introspective and sometimes roguish lyrics around.

Sickology 101 brims with stellar appearances from lyrical heavyweights. On the opening title track, TECH N9NE slays alongside Chino XL and Crooked I, pulling listeners into the Hip-Hop classroom for a lesson in murdering a beat. It`s a twisted vision forged on undeniable grooves and quixotic wordplay.

The single, “Nothin,`” is an inspiring, honest anthem that features Messy Marv and Big Scoob. Meanwhile, on “Midwest Choppers 2,” TECH N9NE and Krayzie Bone cruise to the depths of darkness. “Krayzie Bone came through and murdered it,” says TECH N9NE. “I modeled the song after movies. When you do a sequel, there has to be a bigger body count and more people have to die. ‘Midwest Choppers 2` is Autobahn-style. It makes you want to speed.”

TECH N9NE`s inimitable flow and rhyming take center stage on solo tracks, including the haunting, hypnotic “Red Nose.” He doesn`t pull any punches on the vitriolic, YoungFyre-produced “Blown Away,” either. It`s an open letter to several prominent urban artists who refused to play before him at radio festivals despite his massive concert draw.

With hits like “I`m A Playa,” “Caribou Lou” (which boasts 7.2 million MySpace plays), “Riotmaker,” “Like Yeah” and “Everybody Move,” it`s no wonder TECH N9NE counts a total of over 4.5 million YouTube video plays and an average of 40,000 MySpace visitors each day. His success knows no limits. The July 2008 release, Killer, debuted at Number 1 on the Billboard Top Independent Albums chart and Number 12 on the Billboard Top 200 Albums chart. He did it all on his own. There was no major label — just TECH N9NE`s own record company, Strange Music. TECH N9NE`s tracks have appeared in films like Gang Related and Alpha Dog as well as various TV shows, and he recently made his motion picture debut in The Life of Lucky Cucumber alongside members of MTV`s “Jackass” crew.

It hasn`t been an easy road, but TECH N9NE soldiers on and he`ll never stop. “They call me devil worshipper because I`m different. I give you music for my core. They`re the people that put me over the million mark. I raise my middle finger to everybody who judges me because my core audience is there for me. They will always love me, but I`m trying to reach others, too. It`s not over. My music is supposed to be for everybody, but some people just don`t get it. This album is the result; swallow it. It`s middle finger music, all-day and all-night.”

TECH N9NE never stops bringing that music directly to his fans, constantly reinforcing his status as one of the hardest-touring rap acts in the business. In 2008, TECH N9NE performed over 200 shows and he doesn`t show any signs of slowing down in 2009. In April, TECH will head out in support of Sickology 101 and spend two months on the road, performing live for his rabid fans.

Sickology 101 is prepping the world for TECH N9NE`s next masterpiece, K.O.D. “I want people to know that I`m getting better and better and I`m a machine. I do these collabo albums to give the fans more. This is a bridge record to K.O.D. It`s the farewell to the TECH N9NE you`ve known lately. It`s getting darker. A lot of people might not be able to go to the place I`m going, but this place is my specialty.”

“I don`t need people to kiss my hand,” assures TECH N9NE. “I`m not trippin` on status, and I`m not a narcissist when it comes to rap. It`s my heart and soul pouring onto the paper. I write my life and I can`t hold back. This is what I know.”", image: "https://www.billboard.com/wp-content/uploads/media/Tech-N9ne-2018-cr-denny-illic-billboard-1548.jpg")
Artist.create!(name: "Słoń", years_active: "2009-present", bio: "Słoń is a Polish rapper from Poznań who represents the horrorcore trend. It is the most famous representative of this subspecies in Poland. He leads a solo career and co-creates the composition of WSRH and Demonologia (Słoń & Mikser).

He started his artistic activity in the first decade of the 21st century, however, he made his first attempts at raping during his school days. In 2009, Słoń solo debut entitled Chore melodies was released. The material was kept in a horrorcore style that was not very popular on the domestic market at that time and made the rapper popular in the artistic underground.",  image: "https://i1.sndcdn.com/artworks-YHDDbHUohxgI5Jd4-LOcTwQ-t500x500.jpg")
Artist.create!(name: "Brotha Lynch Hung", years_active: "1993-present", bio: "Brotha Lynch Hung (born Kevin Mann) is an MC and producer from Sacramento, CA who began rapping at 13. Lynch Hung's lyrics are notorious for featuring highly explicit themes, including murder, rape and cannibalism. Lynch Hung debuted with the 1993 album 24 Deep, which featured stories of the struggles involved with being affiliated with a local street gang in Sacramento's 'Garden Blocc.' Lynch Hung has also helped Master P with albums like I'm Bout It, E-40's Southwest Riders and Mr. Serv-On's Life Insurance. Lynch's first known work is his production for X-Raided's 'Niggas In Blacc' (91) and the callaboration album 'Nigga Deep' with Triple Sicx Bounty, released in 1992 and re-released in 1998.

Brotha Lynch Hung has been described as the creator of the 'horrorcore rap genre', and has sold 1.4 million cds independently. His rapping style has been described as smooth and quickly delivered.

Some listeners argue that Lynch Hung's 24 Deep album defines his musical style, but Lynch Hung has said in interviews and online forums that it does not.

Lynch Hung's second album Season of Da Siccness in 1995 proved to be the one of the most gruesome and mysogynistic Gangsta Rap albums ever released, graphically chronicling a life of drug use and sale, promiscuity, ultra-violence, rape, infanticide, and supposed cannibalism. This is Lynch's most commercially successful album, as it has now achieved gold album sales status.

Lynch Hung's lyrics are described as sicc -\ having the same meaning as the word sick but utilizing the double 'C' which is characteristic of local Crip gangsters (loccs) in Sacramento, CA and other parts of California. Lynch has stated in his song '24 Gone' that he himself is a Crip, residing in Crip areas of Sacramento has had an influence on his lyrics. He has been in gang confrontations, and he was shot once. He describes his real life experiences in his lyrics. He has since released Loaded in 1997. The next Lynch album was released in 2000 called EBK4 after a dispute with Black Market Records. The label allegedly restricted his creativity by featuring artists on the album against Lynch's will. Lynch asked his fans not to buy the album. He said 'I don't care how they get it just don't buy it or steal it'. Brotha Lynch released the DVD of Now Eat in 2000, which features a bloodthirsty and cannibalistic Lynch who goes on a rampage, killing and eating many people.

Lynch released Blocc Movement and Virus in 2001, Appearances: Book 1 in 2002, and in that same summer of 2002 he released his first DVD, Plague. Lynch's newer work includes Lynch by Inch: Suicide Note and Uthanizm in 2003, and the Now Eat DVD in 2000. In 2006 he released a collaboration with rapper MC Eiht entitiled 'The New Season.'

In May 2009, Mann signed a three album deal with Midwest rapper Tech N9ne's Strange Music label. In March 2010, he released his Strange Music debut, Dinner and a Movie, selling around 7,000 copies during its first week. His second Strange album, Coathanga Strangla, was released a year later in April 2011, and his third album with Strange Music, Mannibalector was released on February 5, 2013. The Horror-inspired trilogy told a fictional story of a crazed cannibalistic serial killer, struggling with life, family and the urge to kill. Each album debuted on the Billboard 200, and featured acts such as Snoop Dogg, Yelawolf, Hopsin and Tech N9ne among others. Following the release of the third album, Strange Music offered Mann a contract extension to keep him on the label.", image: "https://bandwagmag.com/wp-content/uploads/2017/09/Lynch-Blood-All-Over-Me-1.jpg")
Artist.create!(name: "Dark Lotus", years_active: "1998-2017", bio: "Dark Lotus is an American hip-hop supergroup based in Detroit, Michigan. Formed in 1998, the group consists of Psychopathic Records-associated rappers Joseph Bruce and Joseph Utsler of Insane Clown Posse, Jamie Spaniolo and Paul Methric of Twiztid, and Blaze Ya Dead Homie.

Dark Lotus made its debut with the single 'Echo Side', which was later released on Insane Clown Posse's 1999 album The Amazing Jeckel Brothers. It was later announced that each member 'would act as a 'petal' of the lotus,' and that there would be six members. After speculation as to who the sixth member would be, including rumors that Esham would join the group, it was announced that Marz would be a member.
  
Dark Lotus released their first album, Tales from the Lotus Pod, in 2001. Mike E. Clark was brought in to produce the album, but left the project after producing four songs, and Fritz the Cat produced the rest of the album. The album peaked at #1 on the Billboard Heatseekers chart, #6 on the Top Independent Albums chart, and #158 on the Billboard 200. Marz left the group, and was replaced by James Lowery. In 2002, Tales from the Lotus Pod was reissued in a new version removing Marz' vocals. On April 6, 2004, Dark Lotus released their second studio album, Black Rain. It peaked at #3 on the Top Independent Albums chart, and at #71 on the Billboard 200.
  
Lowery left the group, and a third album, The Opaque Brotherhood, was released without him. It peaked at #4 on the Top Independent Albums chart, #23 on the Top R&B/Hip-Hop Albums chart, #45 on the Top Internet Albums chart, and #45 on the Billboard 200. Allrovi reviewer Stewart Mason praised the album, writing 'Nothing on The Opaque Brotherhood will convince anyone who isn't already a fan, but the tormented lyrics and matter-of-fact delivery remove a layer or two of distance and artifice from the band's familiar themes, and make them that much more disturbing as a result.'.", image: "https://lastfm.freetls.fastly.net/i/u/ar0/4979182ee8f847a6c72ac1e82003a25a.jpg")
Artist.create!(name:, years_active:, bio:, image:)
Artist.create!(name:, years_active:, bio:, image:)
Artist.create!(name:, years_active:, bio:, image:)
Artist.create!(name:, years_active:, bio:, image:)
Artist.create!(name:, years_active:, bio:, image:)
Artist.create!(name:, years_active:, bio:, image:)
Artist.create!(name:, years_active:, bio:, image:)
Artist.create!(name:, years_active:, bio:, image:)
Artist.create!(name:, years_active:, bio:, image:)
Artist.create!(name:, years_active:, bio:, image:)
Artist.create!(name:, years_active:, bio:, image:)
Artist.create!(name:, years_active:, bio:, image:)
Artist.create!(name:, years_active:, bio:, image:)
Artist.create!(name:, years_active:, bio:, image:)
Artist.create!(name:, years_active:, bio:, image:)
Artist.create!(name:, years_active:, bio:, image:)
Artist.create!(name:, years_active:, bio:, image:)
Artist.create!(name:, years_active:, bio:, image:)
Artist.create!(name:, years_active:, bio:, image:)
Artist.create!(name:, years_active:, bio:, image:)
Artist.create!(name:, years_active:, bio:, image:)
Artist.create!(name:, years_active:, bio:, image:)
Artist.create!(name:, years_active:, bio:, image:)
Artist.create!(name:, years_active:, bio:, image:)
Artist.create!(name:, years_active:, bio:, image:)
Artist.create!(name:, years_active:, bio:, image:)
Artist.create!(name:, years_active:, bio:, image:)
Artist.create!(name:, years_active:, bio:, image:)
Artist.create!(name:, years_active:, bio:, image:)